services:
  db:
    image: docker.io/library/postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: wORFJVZH240V
        POSTGRES_DB: movies
    hostname: db.docker.local
    ports:
        - 5432:5432
    volumes:
        - dbdata:/var/lib/postgresql/data
  api:
    image: moviedbapi

    ports:
      - '2222:80'
    depends_on:
    - db

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '<dbPath>'